name: Make an official Release

on: workflow_dispatch

jobs:
  official-release:
    # creates workflows for the 3 OS: ubuntu, macOS & windows
    runs-on: ${{ matrix.os }}

    # The official-release environment requires 2 manual approvals
    environment:
      name: official-release
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04]
    steps:
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          architecture: x64
      - name: Checkout TorchServe
        uses: actions/checkout@v3
      - name: Login to Docker
        env:
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        if: matrix.os == 'ubuntu-20.04'
        run: docker login --username pytorchbot --password "$DOCKER_PASSWORD"
      - name: Build & Upload pytorch/torchserve-kfs Docker images
        if: matrix.os == 'ubuntu-20.04'
        run: |
          cd kubernetes/kserve
          python build_upload_release.py
          cd ..
